// Generated by GG/scripts/sync-game-menus.mjs.
export const GAME_MENU = {
  "selector": "[data-gg-pregame]",
  "steps": {
    "en": [
      "Capture every territory to win. A player who loses their last territory is eliminated.",
      "Place reinforcements on your land, then select a territory and an adjacent enemy to attack with dice.",
      "Move armies into captured land, then fortify a border at the end of your turn. Holding a whole region earns extra reinforcements."
    ],
    "ru": [
      "Захвати всю карту. Игрок, потерявший последнее владение, выбывает.",
      "Расставь подкрепления на своей земле, затем выбери своё владение и соседнее вражеское для атаки кубиками.",
      "Переведи армии на захваченную землю, а в конце хода укрепи границу. Целый регион даёт дополнительные подкрепления."
    ]
  }
}
